//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JimsX10.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TStatCoolAdd {
            get {
                return ((string)(this["TStatCoolAdd"]));
            }
            set {
                this["TStatCoolAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TStatHeatAdd {
            get {
                return ((string)(this["TStatHeatAdd"]));
            }
            set {
                this["TStatHeatAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TStatMixAdd {
            get {
                return ((string)(this["TStatMixAdd"]));
            }
            set {
                this["TStatMixAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TStatRainAdd {
            get {
                return ((string)(this["TStatRainAdd"]));
            }
            set {
                this["TStatRainAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TStatHumidAdd {
            get {
                return ((string)(this["TStatHumidAdd"]));
            }
            set {
                this["TStatHumidAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal TStatMaxTemp {
            get {
                return ((decimal)(this["TStatMaxTemp"]));
            }
            set {
                this["TStatMaxTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal TStatMinTemp {
            get {
                return ((decimal)(this["TStatMinTemp"]));
            }
            set {
                this["TStatMinTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal TStatMaxSplit {
            get {
                return ((decimal)(this["TStatMaxSplit"]));
            }
            set {
                this["TStatMaxSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public string TStatRainMin {
            get {
                return ((string)(this["TStatRainMin"]));
            }
            set {
                this["TStatRainMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal TStatHumidity {
            get {
                return ((decimal)(this["TStatHumidity"]));
            }
            set {
                this["TStatHumidity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TStatUsaApp {
            get {
                return ((bool)(this["TStatUsaApp"]));
            }
            set {
                this["TStatUsaApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TStatBarnCoolAdd {
            get {
                return ((string)(this["TStatBarnCoolAdd"]));
            }
            set {
                this["TStatBarnCoolAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal TStatBarnDesMax {
            get {
                return ((decimal)(this["TStatBarnDesMax"]));
            }
            set {
                this["TStatBarnDesMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal TStatBarnDesMin {
            get {
                return ((decimal)(this["TStatBarnDesMin"]));
            }
            set {
                this["TStatBarnDesMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TStatBarnHeatAdd {
            get {
                return ((string)(this["TStatBarnHeatAdd"]));
            }
            set {
                this["TStatBarnHeatAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TStatBarnUseApp {
            get {
                return ((bool)(this["TStatBarnUseApp"]));
            }
            set {
                this["TStatBarnUseApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TStatBarnSensor {
            get {
                return ((int)(this["TStatBarnSensor"]));
            }
            set {
                this["TStatBarnSensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TStatFreshAdd {
            get {
                return ((string)(this["TStatFreshAdd"]));
            }
            set {
                this["TStatFreshAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public decimal TStatMaxDP {
            get {
                return ((decimal)(this["TStatMaxDP"]));
            }
            set {
                this["TStatMaxDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TempSensorCount {
            get {
                return ((int)(this["TempSensorCount"]));
            }
            set {
                this["TempSensorCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogFilePath {
            get {
                return ((string)(this["LogFilePath"]));
            }
            set {
                this["LogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>True</string>
  <string>False</string>
  <string>False</string>
  <string>False</string>
  <string>False</string>
  <string>False</string>
  <string>False</string>
  <string>False</string>
  <string>False</string>
  <string>False</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CheckBoxes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CheckBoxes"]));
            }
            set {
                this["CheckBoxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDesHumidity {
            get {
                return ((bool)(this["AutoDesHumidity"]));
            }
            set {
                this["AutoDesHumidity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TUnitsdegF {
            get {
                return ((bool)(this["TUnitsdegF"]));
            }
            set {
                this["TUnitsdegF"] = value;
            }
        }
    }
}
